<?php
include_once '../user-auth.php';
include_once '../conf.php';

function str_putcsv($data)
{
    $fh = fopen('php://temp', 'rw'); # don't create a file, attempt
    fputcsv($fh, ["Name", "Status"]);
    foreach ($data as $row) {
        fputcsv($fh, $row);
    }
    rewind($fh);
    $csv = stream_get_contents($fh);
    fclose($fh);
    return $csv;
}

$userCheckedItems = $wf->getData($_SESSION['userData']["uid"]);
$allItems = [
    "Acceltra",
    "Acceltra Prime",
    "Ack & Brunt",
    "Acrid",
    "Adarza Kavat",
    "Aegrit",
    "Aeolak",
    "Afentis",
    "Afuris",
    "Afuris Prime",
    "Agkuza",
    "Akarius",
    "Akarius Prime",
    "Akaten (Hec Hound)",
    "Akbolto",
    "Akbolto Prime",
    "Akbronco",
    "Akbronco Prime",
    "Akjagara",
    "Akjagara Prime",
    "Aklato",
    "Aklex",
    "Aklex Prime",
    "Akmagnus",
    "Akmagnus Prime",
    "Aksomati",
    "Aksomati Prime",
    "Akstiletto",
    "Akstiletto Prime",
    "Akvasto",
    "Akvasto Prime",
    "Akzani",
    "Alternox",
    "Amanata",
    "Ambassador",
    "Amesha",
    "Amphis",
    "Amprex",
    "Angstrum",
    "Anku",
    "Ankyros",
    "Ankyros Prime",
    "Arca Plasmor",
    "Arca Scisco",
    "Arca Titron",
    "Argo & Vel",
    "Argonak",
    "Artax",
    "Arum Spinosa",
    "Ash",
    "Ash Prime",
    "Astilla",
    "Astilla Prime",
    "Athodai",
    "Atlas",
    "Atlas Prime",
    "Atomos",
    "Atterax",
    "Attica",
    "Ax-52",
    "Azima",
    "Azothane",
    "Bad Baby",
    "Balla Strike",
    "Ballistica",
    "Ballistica Prime",
    "Banshee",
    "Banshee Prime",
    "Baruuk",
    "Baruuk Prime",
    "Basmu",
    "Batoten (Dorma Hound)",
    "Battacor",
    "Baza",
    "Baza Prime",
    "Bhaira Hound",
    "Bo",
    "Bo Prime",
    "Boar",
    "Boar Prime",
    "Boltace",
    "Bolto",
    "Boltor",
    "Boltor Prime",
    "Bonewidow",
    "Brakk",
    "Braton",
    "Braton Prime",
    "Braton Vandal",
    "Broken Scepter",
    "Broken War",
    "Bronco",
    "Bronco Prime",
    "Bubonico",
    "Burst Laser",
    "Burst Laser Prime",
    "Burston",
    "Burston Prime",
    "Buzlok",
    "Cadus",
    "Caliban",
    "Cantare",
    "Cantic Prism",
    "Carmine Penta",
    "Carrier",
    "Carrier Prime",
    "Cassowar",
    "Castanas",
    "Catabolyst",
    "Catchmoon",
    "Caustacyst",
    "Cedo",
    "Centaur",
    "Ceramic Dagger",
    "Cerata",
    "Cernos",
    "Cernos Prime",
    "Cestra",
    "Ceti Lacera",
    "Chesa Kubrow",
    "Chroma",
    "Chroma Prime",
    "Cinta",
    "Citrine",
    "Cobra & Crane",
    "Cobra & Crane Prime",
    "Convectrix",
    "Corinth",
    "Corinth Prime",
    "Cortege",
    "Corufell",
    "Corvas",
    "Corvas Prime",
    "Crescent Vulpaphyla",
    "Cronus",
    "Cryotra",
    "Cyanex",
    "Cyath Strike",
    "Cycron",
    "Cyngas",
    "Cyte-09",
    "Dagath",
    "Daikyu",
    "Dakra Prime",
    "Dante",
    "Dark Dagger",
    "Dark Split-Sword",
    "Dark Sword",
    "Deconstructor",
    "Deconstructor Prime",
    "Dehtat Strike",
    "Dera",
    "Dera Vandal",
    "Despair",
    "Destreza",
    "Destreza Prime",
    "Deth Machine Rifle",
    "Deth Machine Rifle Prime",
    "Dethcube",
    "Dethcube Prime",
    "Detron",
    "Dex Dakra",
    "Dex Furis",
    "Dex Nikana",
    "Dex Sybaris",
    "Diriga",
    "Djinn",
    "Dokrahm Strike",
    "Dorma Hound",
    "Dorrclave",
    "Dragon Nikana",
    "Drakgoon",
    "Dread",
    "Dual Cestra",
    "Dual Cleavers",
    "Dual Decurion",
    "Dual Ether",
    "Dual Heat Swords",
    "Dual Ichor",
    "Dual Kamas",
    "Dual Kamas Prime",
    "Dual Keres",
    "Dual Keres Prime",
    "Dual Raza",
    "Dual Skana",
    "Dual Toxocyst",
    "Dual Zoren",
    "Edun",
    "Ekhein",
    "Elytron",
    "Ember",
    "Ember Prime",
    "Embolist",
    "Endura",
    "Epitaph",
    "Epitaph Prime",
    "Equinox",
    "Equinox Prime",
    "Ether Daggers",
    "Ether Reaper",
    "Ether Sword",
    "Euphona Prime",
    "Evensong",
    "Excalibur",
    "Excalibur Umbra",
    "Exergis",
    "Falcor",
    "Fang",
    "Fang Prime",
    "Felarx",
    "Ferrox",
    "Feverspine",
    "Flatbelly",
    "Fluctus",
    "Flux Rifle",
    "Fragor",
    "Fragor Prime",
    "Frost",
    "Frost Prime",
    "Fulmin",
    "Fulmin Prime",
    "Furax",
    "Furax Wraith",
    "Furis",
    "Fusilai",
    "Galatine",
    "Galatine Prime",
    "Galvacord",
    "Gammacor",
    "Gara",
    "Gara Prime",
    "Garuda",
    "Garuda Prime",
    "Gauss",
    "Gauss Prime",
    "Gazal Machete",
    "Gaze",
    "Ghoulsaw",
    "Glaive",
    "Glaive Prime",
    "Glaxion",
    "Glaxion Vandal",
    "Gorgon",
    "Gorgon Wraith",
    "Gotva Prime",
    "Grakata",
    "Gram",
    "Gram Prime",
    "Granmu Prism",
    "Grattler",
    "Grendel",
    "Grendel Prime",
    "Grimoire",
    "Grinlok",
    "Guandao",
    "Guandao Prime",
    "Gunsen",
    "Gunsen Prime",
    "Gyre",
    "Halikar",
    "Halikar Wraith",
    "Harmony",
    "Harpak",
    "Harrow",
    "Harrow Prime",
    "Hate",
    "Heat Dagger",
    "Heat Sword",
    "Hec Hound",
    "Hek",
    "Heliocor",
    "Helios",
    "Helios Prime",
    "Helminth Charger",
    "Helstrum",
    "Hema",
    "Hespar",
    "Higasa",
    "Hikou",
    "Hikou Prime",
    "Hildryn",
    "Hildryn Prime",
    "Hind",
    "Hirudo",
    "Huras Kubrow",
    "Hydroid",
    "Hydroid Prime",
    "Hystrix",
    "Hystrix Prime",
    "Ignis",
    "Ignis Wraith",
    "Imperator",
    "Imperator Vandal",
    "Inaros",
    "Inaros Prime",
    "Innodem",
    "Itzal",
    "Ivara",
    "Ivara Prime",
    "Jade",
    "Jat Kittag",
    "Jat Kusar",
    "Javlok",
    "Jaw Sword",
    "Kama",
    "Karak",
    "Karak Wraith",
    "Karyst",
    "Karyst Prime",
    "Kaszas",
    "Keratinos",
    "Kesheg",
    "Kestrel",
    "Khora",
    "Khora Prime",
    "Klamora Prism",
    "Knell",
    "Knell Prime",
    "Knux",
    "Kogake",
    "Kogake Prime",
    "Kohm",
    "Kohmak",
    "Komorex",
    "Kompressa",
    "Korrudo",
    "Korumm",
    "Koumei",
    "Kraken",
    "Kreska",
    "Krohkur",
    "Kronen",
    "Kronen Prime",
    "Kronsh Strike",
    "Kullervo",
    "Kulstar",
    "Kunai",
    "Kuva Ayanga",
    "Kuva Brakk",
    "Kuva Bramma",
    "Kuva Chakkhurr",
    "Kuva Drakgoon",
    "Kuva Grattler",
    "Kuva Hek",
    "Kuva Hind",
    "Kuva Karak",
    "Kuva Kohm",
    "Kuva Kraken",
    "Kuva Nukor",
    "Kuva Ogris",
    "Kuva Quartakk",
    "Kuva Seer",
    "Kuva Shildeg",
    "Kuva Sobek",
    "Kuva Tonkor",
    "Kuva Twin Stubbas",
    "Kuva Zarr",
    "Lacera",
    "Lacerten (Bhaira Hound)",
    "Laetum",
    "Lambeo Moa",
    "Lanka",
    "Larkspur",
    "Larkspur Prime",
    "Laser Rifle",
    "Lato",
    "Lato Vandal",
    "Latron",
    "Latron Prime",
    "Latron Wraith",
    "Lavos",
    "Lecta",
    "Lega Prism",
    "Lenz",
    "Lesion",
    "Lex",
    "Lex Prime",
    "Limbo",
    "Limbo Prime",
    "Loki",
    "Loki Prime",
    "Machete",
    "Machete Wraith",
    "Mag",
    "Mag Prime",
    "Magistar",
    "Magnus",
    "Magnus Prime",
    "Mandonel",
    "Mara Detron",
    "Marelok",
    "Masseter",
    "Masseter Prime",
    "Mausolon",
    "Medjay Predasite",
    "Mesa",
    "Mesa Prime",
    "Mewan Strike",
    "Mios",
    "Mirage",
    "Mirage Prime",
    "Mire",
    "Miter",
    "Mk1-Bo",
    "Mk1-Braton",
    "Mk1-Furax",
    "Mk1-Furis",
    "Mk1-Kunai",
    "Mk1-Paris",
    "Mk1-Strun",
    "Morgha",
    "Mote Prism",
    "Multron",
    "Mutalist Cernos",
    "Mutalist Quanta",
    "Nagantaka",
    "Nagantaka Prime",
    "Nami Skyla",
    "Nami Skyla Prime",
    "Nami Solo",
    "Nataruk",
    "Nautilus",
    "Nautilus Prime",
    "Needlenose",
    "Nekros",
    "Nekros Prime",
    "Nepheri",
    "Nezha",
    "Nezha Prime",
    "Nidus",
    "Nidus Prime",
    "Nikana",
    "Nikana Prime",
    "Ninkondi",
    "Ninkondi Prime",
    "Nova",
    "Nova Prime",
    "Nukor",
    "Nychus Moa",
    "Nyx",
    "Nyx Prime",
    "Oberon",
    "Oberon Prime",
    "Obex",
    "Octavia",
    "Octavia Prime",
    "Ocucor",
    "Odonata",
    "Odonata Prime",
    "Ogris",
    "Ohma",
    "Okina",
    "Okina Prime",
    "Oloro Moa",
    "Onorix",
    "Onos",
    "Ooltha Strike",
    "Opticor",
    "Opticor Vandal",
    "Orthos",
    "Orthos Prime",
    "Orvius",
    "Oxylus",
    "Pandero",
    "Pandero Prime",
    "Pangolin Prime",
    "Pangolin Sword",
    "Panthera",
    "Panthera Prime",
    "Panzer Vulpaphyla",
    "Para Moa",
    "Paracesis",
    "Paracyst",
    "Paris",
    "Paris Prime",
    "Pathocyst",
    "Pennant",
    "Penta",
    "Perigale",
    "Phaedra",
    "Phage",
    "Phantasma",
    "Phantasma Prime",
    "Pharaoh Predasite",
    "Phenmor",
    "Plague Keewar Strike",
    "Plague Kripath Strike",
    "Plasma Sword",
    "Plexus",
    "Plinx",
    "Pox",
    "Praedos",
    "Prime Laser Rifle",
    "Prisma Angstrum",
    "Prisma Burst Laser",
    "Prisma Dual Cleavers",
    "Prisma Dual Decurions",
    "Prisma Gorgon",
    "Prisma Grakata",
    "Prisma Grinlok",
    "Prisma Lenz",
    "Prisma Machete",
    "Prisma Obex",
    "Prisma Ohma",
    "Prisma Shade",
    "Prisma Skana",
    "Prisma Tetra",
    "Prisma Twin Gremlins",
    "Prisma Veritux",
    "Proboscis Cernos",
    "Protea",
    "Protea Prime",
    "Prova",
    "Prova Vandal",
    "Pulmonars",
    "Pupacyst",
    "Pyrana",
    "Pyrana Prime",
    "Qorvex",
    "Quanta",
    "Quanta Vandal",
    "Quartakk",
    "Quassus",
    "Quassus Prime",
    "Quatz",
    "Quellor",
    "Rabvee Strike",
    "Rahn Prism",
    "Raksa Kubrow",
    "Rakta Ballistica",
    "Rakta Cernos",
    "Rakta Dark Dagger",
    "Raplak Prism",
    "Rathbone",
    "Rattleguts",
    "Rauta",
    "Reaper Prime",
    "Reconifex",
    "Redeemer",
    "Redeemer Prime",
    "Revenant",
    "Revenant Prime",
    "Rhino",
    "Rhino Prime",
    "Ripkas",
    "Rubico",
    "Rubico Prime",
    "Rumblejack",
    "Runway",
    "Ruvox",
    "Sahasa Kubrow",
    "Sampotes",
    "Sancti Castanas",
    "Sancti Magistar",
    "Sancti Tigris",
    "Sarofang",
    "Sarpa",
    "Saryn",
    "Saryn Prime",
    "Scindo",
    "Scindo Prime",
    "Scoliac",
    "Scourge",
    "Scourge Prime",
    "Secura Dual Cestra",
    "Secura Lecta",
    "Secura Penta",
    "Seer",
    "Sepfahn Strike",
    "Sepulcrum",
    "Serro",
    "Sevagoth",
    "Sevagoth Prime",
    "Shade",
    "Shade Prime",
    "Shaku",
    "Shedu",
    "Sheev",
    "Shwaak Prism",
    "Sibear",
    "Sicarus",
    "Sicarus Prime",
    "Sigma & Octantis",
    "Silva & Aegis",
    "Silva & Aegis Prime",
    "Simulor",
    "Sirocco",
    "Skana",
    "Skiajati",
    "Slaytra",
    "Sly Vulpaphyla",
    "Smeeta Kavat",
    "Snipetron",
    "Snipetron Vandal",
    "Sobek",
    "Soma",
    "Soma Prime",
    "Sonicor",
    "Spectra",
    "Spectra Vandal",
    "Spira",
    "Spira Prime",
    "Sporelacer",
    "Sporothrix",
    "Stahlta",
    "Staticor",
    "Steflos",
    "Stinger",
    "Stradavar",
    "Stradavar Prime",
    "Stropha",
    "Strun",
    "Strun Prime",
    "Strun Wraith",
    "Stubba",
    "Stug",
    "Styanax",
    "Sun & Moon",
    "Sunika Kubrow",
    "Supra",
    "Supra Vandal",
    "Sweeper",
    "Sweeper Prime",
    "Syam",
    "Sybaris",
    "Sybaris Prime",
    "Sydon",
    "Synapse",
    "Synoid Gammacor",
    "Synoid Heliocor",
    "Synoid Simulor",
    "Talons",
    "Tatsu",
    "Tatsu Prime",
    "Taxon",
    "Tazicor",
    "Tekko",
    "Tekko Prime",
    "Telos Akbolto",
    "Telos Boltace",
    "Telos Boltor",
    "Tenet Agendus",
    "Tenet Arca Plasmor",
    "Tenet Cycron",
    "Tenet Detron",
    "Tenet Diplos",
    "Tenet Envoy",
    "Tenet Exec",
    "Tenet Ferrox",
    "Tenet Flux Rifle",
    "Tenet Glaxion",
    "Tenet Grigori",
    "Tenet Livia",
    "Tenet Plinx",
    "Tenet Spirex",
    "Tenet Tetra",
    "Tenora",
    "Tenora Prime",
    "Tetra",
    "Tiberon",
    "Tiberon Prime",
    "Tigris",
    "Tigris Prime",
    "Tipedo",
    "Tipedo Prime",
    "Titania",
    "Titania Prime",
    "Tombfinger",
    "Tonbo",
    "Tonkor",
    "Torid",
    "Trinity",
    "Trinity Prime",
    "Trumna",
    "Trumna Prime",
    "Twin Basolk",
    "Twin Grakatas",
    "Twin Gremlins",
    "Twin Kohmak",
    "Twin Krohkur",
    "Twin Rogga",
    "Twin Vipers",
    "Twin Vipers Wraith",
    "Tysis",
    "Valkyr",
    "Valkyr Prime",
    "Vasca Kavat",
    "Vastilok",
    "Vasto",
    "Vasto Prime",
    "Vauban",
    "Vauban Prime",
    "Vaykor Hek",
    "Vaykor Marelok",
    "Vaykor Sydon",
    "Vectis",
    "Vectis Prime",
    "Veldt",
    "Velocitus",
    "Velox",
    "Velox Prime",
    "Venato",
    "Venka",
    "Venka Prime",
    "Verdilac",
    "Verglas",
    "Verglas Prime",
    "Vericres",
    "Veritux",
    "Vermisplicer",
    "Vesper 77",
    "Viper",
    "Viper Wraith",
    "Vitrica",
    "Vizier Predasite",
    "Voidrig Necramech",
    "Volnus",
    "Volnus Prime",
    "Volt",
    "Volt Prime",
    "Voruna",
    "Vulcax",
    "Vulkar",
    "Vulkar Wraith",
    "Vulklok",
    "War",
    "Wisp",
    "Wisp Prime",
    "Wolf Sledge",
    "Wukong",
    "Wukong Prime",
    "Wyrm",
    "Wyrm Prime",
    "Xaku",
    "Xaku Prime",
    "Xoris",
    "Yareli",
    "Zakti",
    "Zakti Prime",
    "Zarr",
    "Zenistar",
    "Zenith",
    "Zephyr",
    "Zephyr Prime",
    "Zhuge",
    "Zhuge Prime",
    "Zylok",
    "Zylok Prime",
    "Zymos",
];

$result = [];
foreach ($allItems as $key => $item) {
    if (in_array($item, $userCheckedItems["data"], false)) {
        array_push($result, [$item, "Checked"]);
    } else {
        array_push($result, [$item, ""]);
    }
}
$output = str_putcsv($result);

header('Content-Type: application/csv');
header('Content-Disposition: attachment; filename="warframe-mastery.csv";');
echo $output;
